[profile.default]
src = 'contracts'
test = 'poc'
out = 'poc/out'
libs = ['lib']
no_match_path = "contracts/*"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 9_999_999
viaIR = false
gas_limit = 9223372036854775807
# eth_rpc_url = "${MAINNET_RPC_URL}" # Commented out for local-only PoC tests
fs_permissions = [{ access = "read", path = "./"}]

[profile.prod]
test='DO_NOT_COMPILE'
script="DO_NOT_COMPILE"

[profile.ci_test]
fork_block_number = 18963715

[profile.ci_sizes]
optimizer_runs = 216
test = 'DO_NOT_COMPILE'

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function", "unaliased-plain-import", "unsafe-cheatcode", "unsafe-typecast"]

[profile.ci_sizes_ir]
optimizer_runs = 200
test = 'DO_NOT_COMPILE'
viaIR = true

[fuzz]
# temporary workaround while we figure out perf issues + configure different test sets + profiles
runs = 30
max_test_rejects = 9_999_999
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
